os: osx
osx_image: xcode11.3
language: swift
script:
  - echo "import Foundation; class AppConfig { static let LegoApiKey = \"$API_KEY\"}" >> LegoIos/AppConfig.swift
  - java -jar WireMock/wiremock.jar --root-dir WireMock --port 9999 &
  - xcodebuild clean test -project "LegoIos.xcodeproj" -scheme "LegoIos" -destination "platform=iOS Simulator,name=iPhone 8,OS=latest"
  - pkill -f 'WireMock/wiremock'
  - xcodebuild -project "LegoIos.xcodeproj" -scheme "LegoIos" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
  - gem install slather
  - slather
  - bash <(curl -s https://codecov.io/bash) -f cobertura.xml -X coveragepy -X gcov -X xcode -t $CODECOV_TOKEN
