# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Generate new localized screenshots locally"
  lane :screenshot_local do
    capture_screenshots(scheme: "Fastlane")
  end

	desc "Generate new localized screenshots"
  lane :screenshot do
    capture_screenshots(scheme: "Fastlane")
    upload_to_app_store(skip_binary_upload: true, skip_metadata: true, force: true)
  end

  desc "Push app to beta"
  lane :beta do
    get_certificates()           # invokes cert
    get_provisioning_profile(provisioning_name: "mebius.LegoIos AppStore")   # invokes sigh
    increment_build_number
    build_app(scheme: "LegoIos")
    upload_to_testflight(skip_waiting_for_build_processing: true)
    slack(
      message: "Successfully distributed a new beta build"
    )
    commit_version_bump
  end

end
